import { assertAdmin } from "@/lib/assertAdmin";
import { createAdminClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

// Ambassador Program (Phase F) — create a new Ambassador from an existing
// Ringo Connect account, looked up by username (the same public,
// already-searched-by-admins identifier used throughout /admin/requests
// and everywhere else). Admin-only. Writes only ambassador_profiles'
// own non-financial columns (user_id/team_id/status/created_by) — the
// row's sales_code is generated by the approved DB trigger, never chosen
// here. Every action is logged to ambassador_admin_actions, the
// Ambassador program's own audit trail, separate from the existing
// admin_audit_log.
export async function POST(request: Request) {
  const admin = await assertAdmin();
  if (!admin) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const body = await request.json().catch(() => null);
  const username = typeof body?.username === "string" ? body.username.trim().toLowerCase() : "";
  const teamId = typeof body?.teamId === "string" && body.teamId ? body.teamId : null;
  if (!username) return NextResponse.json({ error: "A username is required." }, { status: 400 });

  const adminClient = createAdminClient();
  const { data: profile } = await adminClient.from("profiles").select("user_id, username").eq("username", username).maybeSingle();
  if (!profile) return NextResponse.json({ error: "No profile found with that username." }, { status: 404 });

  if (teamId) {
    const { data: team } = await adminClient.from("ambassador_teams").select("id").eq("id", teamId).maybeSingle();
    if (!team) return NextResponse.json({ error: "That team does not exist." }, { status: 404 });
  }

  const { data: existing } = await adminClient.from("ambassador_profiles").select("id").eq("user_id", profile.user_id).maybeSingle();
  if (existing) return NextResponse.json({ error: "This account is already an Ambassador." }, { status: 409 });

  const { data: created, error } = await adminClient
    .from("ambassador_profiles")
    .insert({ user_id: profile.user_id, team_id: teamId, status: "active", created_by: admin.id })
    .select("id, sales_code, status, team_id")
    .single();
  if (error || !created) {
    console.error("ambassador create failed:", error?.message);
    return NextResponse.json({ error: "Could not create the Ambassador." }, { status: 500 });
  }

  await adminClient.from("ambassador_admin_actions").insert({
    actor_user_id: admin.id,
    action: "ambassador_created",
    target_table: "ambassador_profiles",
    target_id: created.id,
    before: null,
    after: { user_id: profile.user_id, username: profile.username, team_id: teamId, status: "active", sales_code: created.sales_code },
    reason: null,
  });

  return NextResponse.json({ ok: true, ambassador: created });
}
