// Split out of src/lib/branding.ts on purpose: that file imports
// createAdminClient from src/lib/supabase/server.ts, which itself
// imports next/headers — fine for the server components/routes that use
// getBrandingSettings(), but it means importing ANYTHING from
// branding.ts (even just this type/constant) into a Client Component's
// module graph fails the build ("next/headers ... not supported").
// AuthShell.tsx is a Client Component (every one of the 7 auth pages
// that render it has "use client" at the top), so it imports its
// starting values from here instead — see its own comment for how it
// gets the live, admin-configured values afterward.
export type BrandingSettings = {
  appName: string;
  shortName: string;
  logoUrl: string;
  faviconUrl: string;
  primaryColor: string;
  pwaThemeColor: string;
  pwaBackgroundColor: string;
};

export const DEFAULT_BRANDING: BrandingSettings = {
  appName: "Ringo Connect",
  shortName: "Ringo",
  logoUrl: "/logo.png",
  faviconUrl: "/favicon.ico",
  primaryColor: "#4F46E5",
  pwaThemeColor: "#4F46E5",
  pwaBackgroundColor: "#FAFAF8",
};

// True when an admin has uploaded their own logo in /admin/branding (anything
// other than the bundled default) — that upload keeps overriding the default.
export function hasCustomLogo(logoUrl?: string | null): boolean {
  return !!logoUrl && logoUrl !== DEFAULT_BRANDING.logoUrl;
}

// The installed-app icon set: the official Ringo R symbol on a solid square
// (generated by scripts/generate-pwa-icons.js). Used by the dashboard/admin
// manifests when no custom logo has been uploaded — DEFAULT_BRANDING.logoUrl
// is the transparent R used inside the UI, which makes a poor launcher icon.
export const DEFAULT_APP_ICONS = [
  { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
  { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
  { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
];
