// A Team Leader adds THEIR OWN account as an Ambassador, so they can register
// clients themselves and earn both shares on them (the Ambassador share and the
// Team Leader share — the existing commission rules, unchanged: a sale by an
// Ambassador on a team pays the Ambassador AND that team's leader, and here
// they are the same person).
//
// No new direct-sale model, no schema change: it simply creates the same
// ambassador_profiles row an admin would (Admin -> Ambassadors -> "Make
// Ambassador"), with the team fixed to the Team Leader's OWN team. The
// identity comes from the caller's verified session only; nothing in a request
// body is used. It can NEVER reactivate: if a profile already exists in any
// state other than active (an admin deactivated or suspended it), it is left
// exactly as it is and refused. The Ambassador's sales_code is generated by the
// existing database trigger, never chosen here. Audited in ambassador_admin_actions.
export type SelfEnableErrorCode = "not_team_leader" | "team_inactive" | "profile_inactive" | "demo" | "unavailable";

export async function enableSelfAsAmbassador(admin: any, userId: string): Promise<{ ok: true; salesCode: string; already: boolean } | { ok: false; code: SelfEnableErrorCode }> {
  // Demo accounts never enter real Ambassador programs.
  const { data: demoProfile } = await admin.from("profiles").select("is_demo").eq("user_id", userId).maybeSingle();
  if (demoProfile?.is_demo) return { ok: false, code: "demo" };

  const { data: team } = await admin.from("ambassador_teams").select("id, status").eq("team_leader_user_id", userId).maybeSingle();
  if (!team) return { ok: false, code: "not_team_leader" };
  if (team.status !== "active") return { ok: false, code: "team_inactive" };

  const readExisting = async () => (await admin.from("ambassador_profiles").select("id, sales_code, status").eq("user_id", userId).maybeSingle()).data;

  const existing = await readExisting();
  if (existing) {
    return existing.status === "active" ? { ok: true, salesCode: existing.sales_code, already: true } : { ok: false, code: "profile_inactive" };
  }

  const { data: created, error } = await admin
    .from("ambassador_profiles")
    .insert({ user_id: userId, team_id: team.id, status: "active", created_by: userId })
    .select("id, sales_code, status, team_id")
    .single();
  if (error || !created) {
    // A concurrent double-click loses the unique(user_id) race: fall back to the winner's row.
    const winner = await readExisting();
    if (winner && winner.status === "active") return { ok: true, salesCode: winner.sales_code, already: true };
    console.error("ambassador self-enable failed:", error?.message);
    return { ok: false, code: "unavailable" };
  }

  try {
    await admin.from("ambassador_admin_actions").insert({
      actor_user_id: userId,
      action: "ambassador_self_enabled",
      target_table: "ambassador_profiles",
      target_id: created.id,
      before: null,
      after: { user_id: userId, team_id: team.id, status: "active", sales_code: created.sales_code },
      reason: null,
    });
  } catch (err: any) {
    console.error("ambassador self-enable audit failed:", err?.message);
  }
  return { ok: true, salesCode: created.sales_code, already: false };
}
