// The EXACT files the performance project (phases 2-6: image delivery and upload sizing, the public-profile request waterfall, the owner check, branding cache, JavaScript / rendering,
// caching and navigation, mobile) changes or adds, together with the earlier uncommitted work it sits on top of. Performance only: no payment, Fapshi, Stripe, authentication,
// authorization, RLS, inventory, order, payout, commission or music-preview logic is changed. Same convention as phase25Files.mjs: explicit, no wildcards, no directories.
export const PHASE26_FILES = new Set([
  "next.config.js",
  "public/brand/ringo-symbol-96.png",
  "scripts/tests/avatarShape.test.mjs",
  "scripts/tests/catalogCardAndCardBundle.test.mjs",
  "scripts/tests/categorySubcategories.test.mjs",
  "scripts/tests/designFoundation.test.mjs",
  "scripts/tests/digitalProducts.test.mjs",
  "scripts/tests/heroActionPins.json",
  "scripts/tests/i18nSource.mjs",
  "scripts/tests/landingHero.test.mjs",
  "scripts/tests/musicProfile.test.mjs",
  "scripts/tests/ownerWorkspaceFiles.mjs",
  "scripts/tests/performance.test.mjs",
  "scripts/tests/phase16Files.mjs",
  "scripts/tests/phase26Files.mjs",
  "scripts/tests/productCheckout.test.mjs",
  "scripts/tests/protectionManualRefund.test.mjs",
  "scripts/tests/publicExperience.test.mjs",
  "scripts/tests/ringoCardOfflineContact.test.mjs",
  "scripts/tests/scalabilityPhase0.test.mjs",
  "scripts/tests/scalabilityPhase1to5.test.mjs",
  "scripts/tests/seoMetadata.test.mjs",
  "scripts/tests/subscriptionEntitlements.test.mjs",
  "scripts/tests/suspendedProfile.test.mjs",
  "scripts/tests/whatsappSecurityAudit.test.mjs",
  "src/app/[username]/item/[id]/checkout/page.tsx",
  "src/app/[username]/item/[id]/page.tsx",
  "src/app/[username]/page.tsx",
  "src/app/[username]/shop/page.tsx",
  "src/app/admin/branding/page.tsx",
  "src/app/api/admin/branding/route.ts",
  "src/app/dashboard/page.tsx",
  "src/app/layout.tsx",
  "src/app/loading.tsx",
  "src/app/m/[username]/[type]/[id]/page.tsx",
  "src/app/m/[username]/page.tsx",
  "src/app/r/[username]/item/[id]/page.tsx",
  "src/app/r/[username]/page.tsx",
  "src/components/BrandLogo.tsx",
  "src/components/FanRecognitionHeader.tsx",
  "src/components/ImageGallery.tsx",
  "src/components/LanguageProvider.tsx",
  "src/components/ProfileView.tsx",
  "src/components/ShareButton.tsx",
  "src/components/catalog/CatalogSection.tsx",
  "src/components/catalog/ProductDetailView.tsx",
  "src/components/connect/StayConnectedModal.tsx",
  "src/components/editor/AvatarCropperField.tsx",
  "src/components/editor/ImageGalleryUploadField.tsx",
  "src/components/editor/ImageUploadField.tsx",
  "src/components/editor/TrackRow.tsx",
  "src/components/music/EventsSection.tsx",
  "src/components/music/ItemDetailPage.tsx",
  "src/components/music/MusicSection.tsx",
  "src/components/music/MusicStorePage.tsx",
  "src/components/music/ReleasesSection.tsx",
  "src/components/music/profile/MusicArtistView.tsx",
  "src/components/music/profile/MusicDestinationView.tsx",
  "src/components/music/profile/MusicSections.tsx",
  "src/components/onboarding/GetStartedFlow.tsx",
  "src/components/restaurant/FeaturedMenuSection.tsx",
  "src/components/shop/ShopDestination.tsx",
  "src/components/ui/MenuBackdrop.tsx",
  "src/components/ui/MotionScope.tsx",
  "src/components/ui/OptImg.tsx",
  "src/lib/branding.ts",
  "src/lib/i18n/dictionaryRegistry.ts",
  "src/lib/i18n/translations.en.ts",
  "src/lib/i18n/translations.fr.ts",
  "src/lib/i18n/translations.ts",
  "src/lib/imageDownscale.ts",
  "src/lib/imageUrl.ts",
  "src/lib/music/loadDestination.ts",
  "src/lib/profileMetadata.ts",
  "src/lib/publicProfileVisibility.ts",
  "supabase/support/2026-12-16_profile_lookup_indexes.verify.sql",
]);

export const isPhase26File = (f) => PHASE26_FILES.has(String(f).replace(/\\/g, "/"));

// The files of this phase whose NAME falls inside an area an OLDER scope guard protects (the public item checkout PAGE: only its profile read changed, not the checkout flow, a payment
// call or an order): exempted by exact path, never by directory.
export const PHASE26_PROTECTED_FILES = new Set([
  "src/app/[username]/item/[id]/checkout/page.tsx",
  "src/app/m/[username]/page.tsx", // the Music storefront page: only its profile read and owner/plan lookup changed (read-only); the cart, checkout, payment and preview code live elsewhere and are untouched
  "src/app/m/[username]/[type]/[id]/page.tsx", // the Music item page: only its profile read and suspension check changed (read-only)
  "scripts/tests/productCheckout.test.mjs", // only its read of the dictionary text changed (the dictionaries are two modules now); the checkout assertions are untouched
]);
export const isPhase26ProtectedFile = (f) => PHASE26_PROTECTED_FILES.has(String(f).replace(/\\/g, "/"));
