-- "Super creators" — a regular creator (role stays 'creator') that an
-- admin has separately granted permission to APPROVE signup requests.
-- Deliberately narrow, not the same as role = 'admin':
--   - Scoped to their own referrals only — they only ever see/act on
--     signup_requests whose referral_code matches their own
--     affiliate_code (see canReviewerAccessRequest in
--     src/lib/assertAdmin.ts). Someone else's requests are a 404 to them,
--     not just hidden in the UI.
--   - Can only approve — cannot reject, cannot delete, and cannot charge
--     (there's no "Charge now" option in their review screen at all).
--     Every request they can see came from /get-started-affiliate, where
--     paying online is mandatory before the request exists, so charging
--     is never their job — approving just re-records the payment that
--     already happened. Reject/delete/charge/charge-status all stay
--     full-admin-only (see the matching route files).
--   - No access to the rest of /admin — settings, plans, add-ons,
--     affiliate payouts, analytics, or the creators list.
-- See src/lib/assertAdmin.ts (assertCanApproveRequests,
-- canReviewerAccessRequest) and src/app/dashboard/requests/ for where
-- this is enforced/used.
alter table users add column if not exists can_approve_requests boolean not null default false;
